<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
<<<<<<< HEAD
  <suite started-at="2022-11-24T12:48:36 IST" name="Shaurya Suite" finished-at="2022-11-24T12:49:15 IST" duration-ms="38916">
=======
<<<<<<< HEAD
<<<<<<< HEAD
  <suite started-at="2022-09-30T00:58:42 IST" name="Default suite" finished-at="2022-09-30T00:58:42 IST" duration-ms="341">
    <groups>
    </groups>
    <test started-at="2022-09-30T00:58:42 IST" name="Default test" finished-at="2022-09-30T00:58:42 IST" duration-ms="341">
      <class name="com.nagarro.salesforce.utopia.reports.ExtentReportDemo">
        <test-method signature="LoginTest()[pri:0, instance:com.nagarro.salesforce.utopia.reports.ExtentReportDemo@38234a38]" started-at="2022-09-30T00:58:42 IST" name="LoginTest" finished-at="2022-09-30T00:58:42 IST" duration-ms="278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
      </class> <!-- com.nagarro.salesforce.utopia.reports.ExtentReportDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
=======
  <suite started-at="2022-09-27T15:30:26 IST" name="Utopia Regression Suit" finished-at="2022-09-27T15:30:26 IST" duration-ms="215">
=======
  <suite started-at="2022-10-06T15:17:11 IST" name="Default suite" finished-at="2022-10-06T15:17:24 IST" duration-ms="12654">
>>>>>>> main
>>>>>>> 275376ea8d3241d89c5f7af41a95600b09f592a6
    <groups>
    </groups>
    <test started-at="2022-11-24T12:48:36 IST" name="Test" finished-at="2022-11-24T12:49:15 IST" duration-ms="38916">
      <class name="com.nagarro.salesforce.utopia.testcases.LoginFreeCRM">
        <test-method is-config="true" signature="setUpSuite()[pri:0, instance:com.nagarro.salesforce.utopia.testcases.LoginFreeCRM@67304a40]" started-at="2022-11-24T12:48:36 IST" name="setUpSuite" finished-at="2022-11-24T12:48:36 IST" duration-ms="539" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.nagarro.salesforce.utopia.testcases.LoginFreeCRM@67304a40]" started-at="2022-11-24T12:48:36 IST" name="setup" finished-at="2022-11-24T12:48:42 IST" duration-ms="5712" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="appLogin()[pri:0, instance:com.nagarro.salesforce.utopia.testcases.LoginFreeCRM@67304a40]" started-at="2022-11-24T12:48:42 IST" name="appLogin" finished-at="2022-11-24T12:49:14 IST" duration-ms="32192" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"css selector","selector":"*[name='email1']"}
  (Session info: chrome=107.0.5304.107)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'IN-BBBN0F3', ip: '192.168.1.2', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [234be9e0042b059b08f8dddabe448545, findElement {using=name, value=email1}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.107, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\SHAURY~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:57038}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:57038/devtoo..., se:cdpVersion: 107.0.5304.107, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 234be9e0042b059b08f8dddabe448545]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"*[name='email1']"}
  (Session info: chrome=107.0.5304.107)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'IN-BBBN0F3', ip: '192.168.1.2', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [234be9e0042b059b08f8dddabe448545, findElement {using=name, value=email1}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.107, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\SHAURY~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:57038}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:57038/devtoo..., se:cdpVersion: 107.0.5304.107, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 234be9e0042b059b08f8dddabe448545
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy20.sendKeys(Unknown Source)
at com.nagarro.salesforce.utopia.pages.LoginPage.loginToCRM(LoginPage.java:26)
at com.nagarro.salesforce.utopia.testcases.LoginFreeCRM.appLogin(LoginFreeCRM.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appLogin -->
        <test-method is-config="true" signature="tearDownMeathod(org.testng.ITestResult)[pri:0, instance:com.nagarro.salesforce.utopia.testcases.LoginFreeCRM@67304a40]" started-at="2022-11-24T12:49:14 IST" name="tearDownMeathod" finished-at="2022-11-24T12:49:14 IST" duration-ms="265" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=appLogin status=FAILURE method=LoginFreeCRM.appLogin()[pri:0, instance:com.nagarro.salesforce.utopia.testcases.LoginFreeCRM@67304a40] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMeathod -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.nagarro.salesforce.utopia.testcases.LoginFreeCRM@67304a40]" started-at="2022-11-24T12:49:15 IST" name="teardown" finished-at="2022-11-24T12:49:15 IST" duration-ms="574" status="PASS">
          <reporter-output>
          </reporter-output>
<<<<<<< HEAD
        </test-method> <!-- test_case_method4 -->
      </class> <!-- com.nagarro.salesforce.utopia.basic.tests.TestCases1 -->
      <class name="com.nagarro.salesforce.utopia.basic.tests.TestCases2">
        <test-method signature="test_case2_method1()[pri:0, instance:com.nagarro.salesforce.utopia.basic.tests.TestCases2@6aa3a905]" started-at="2022-09-27T15:30:26 IST" name="test_case2_method1" finished-at="2022-09-27T15:30:26 IST" duration-ms="53" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.fail(AssertJUnit.java:70)
at com.nagarro.salesforce.utopia.basic.tests.TestCases2.test_case2_method1(TestCases2.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case2_method1 -->
        <test-method signature="test_case2_method2()[pri:0, instance:com.nagarro.salesforce.utopia.basic.tests.TestCases2@6aa3a905]" started-at="2022-09-27T15:30:26 IST" name="test_case2_method2" finished-at="2022-09-27T15:30:26 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This should be failed: explicit case]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This should be failed: explicit case
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at com.nagarro.salesforce.utopia.basic.tests.TestCases2.test_case2_method2(TestCases2.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case2_method2 -->
        <test-method signature="test_case2_method3()[pri:0, instance:com.nagarro.salesforce.utopia.basic.tests.TestCases2@6aa3a905]" started-at="2022-09-27T15:30:26 IST" name="test_case2_method3" finished-at="2022-09-27T15:30:26 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case2_method3 -->
        <test-method signature="test_case2_method4()[pri:0, instance:com.nagarro.salesforce.utopia.basic.tests.TestCases2@6aa3a905]" started-at="2022-09-27T15:30:26 IST" name="test_case2_method4" finished-at="2022-09-27T15:30:26 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case2_method4 -->
      </class> <!-- com.nagarro.salesforce.utopia.basic.tests.TestCases2 -->
    </test> <!-- Utopia Test -->
  </suite> <!-- Utopia Regression Suit -->
>>>>>>> 98a32ca03f44fa70572c132b979bba9fe2a838d6
=======
        </test-method> <!-- teardown -->
      </class> <!-- com.nagarro.salesforce.utopia.testcases.LoginFreeCRM -->
<<<<<<< HEAD
    </test> <!-- Test -->
  </suite> <!-- Shaurya Suite -->
=======
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
>>>>>>> main
>>>>>>> 275376ea8d3241d89c5f7af41a95600b09f592a6
</testng-results>
