<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-BBBN0F3" failures="4" tests="8" name="Utopia Test" time="0.201" errors="0" timestamp="2022-11-24T12:44:38 IST">
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases2" name="test_case2_method1" time="0.059">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at com.nagarro.salesforce.utopia.basic.tests.TestCases2.test_case2_method1(TestCases2.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_case2_method1 -->
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases2" name="test_case2_method2" time="0.002">
    <failure type="java.lang.AssertionError" message="This should be failed: explicit case">
      <![CDATA[java.lang.AssertionError: This should be failed: explicit case
at com.nagarro.salesforce.utopia.basic.tests.TestCases2.test_case2_method2(TestCases2.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test_case2_method2 -->
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases2" name="test_case2_method3" time="0.002"/>
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases2" name="test_case2_method4" time="0.002"/>
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases1" name="test_case_method1" time="0.003">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at com.nagarro.salesforce.utopia.basic.tests.TestCases1.test_case_method1(TestCases1.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_case_method1 -->
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases1" name="test_case_method2" time="0.003">
    <failure type="java.lang.AssertionError" message="This should be failed: explicit case">
      <![CDATA[java.lang.AssertionError: This should be failed: explicit case
at com.nagarro.salesforce.utopia.basic.tests.TestCases1.test_case_method2(TestCases1.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test_case_method2 -->
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases1" name="test_case_method3" time="0.003"/>
  <testcase classname="com.nagarro.salesforce.utopia.basic.tests.TestCases1" name="test_case_method4" time="0.002"/>
</testsuite> <!-- Utopia Test -->
